// NOVA v016 — DDL AUTO-GENERADO por scripts/gen_ddl.py desde prisma/schema.prisma.
// NO editar a mano: si cambia el esquema, re-ejecutar scripts/stage_vercel.sh
// (que lo regenera) o: npx prisma migrate diff --from-empty \
//   --to-schema-datamodel prisma/schema.prisma --script
// El runtime ejecuta estas sentencias UNA vez por instancia (idempotentes):
// así las tablas se crean solas en Vercel sin depender del build.

export const NOVA_DDL: string[] = [
  "CREATE SCHEMA IF NOT EXISTS \"public\";",
  "CREATE TABLE IF NOT EXISTS \"Contact\" (\n    \"id\" TEXT NOT NULL,\n    \"waId\" TEXT NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"channel\" TEXT NOT NULL DEFAULT 'whatsapp',\n    \"botPaused\" BOOLEAN NOT NULL DEFAULT false,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"lastSeen\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"Contact_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"Message\" (\n    \"id\" TEXT NOT NULL,\n    \"contactId\" TEXT NOT NULL,\n    \"role\" TEXT NOT NULL,\n    \"kind\" TEXT NOT NULL DEFAULT 'text',\n    \"body\" TEXT NOT NULL,\n    \"meta\" TEXT,\n    \"intent\" TEXT,\n    \"latencyMs\" INTEGER,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"Message_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"PriceAlert\" (\n    \"id\" TEXT NOT NULL,\n    \"coinId\" TEXT NOT NULL,\n    \"sym\" TEXT NOT NULL,\n    \"dir\" TEXT NOT NULL,\n    \"price\" DOUBLE PRECISION NOT NULL,\n    \"on\" BOOLEAN NOT NULL DEFAULT true,\n    \"fired\" BOOLEAN NOT NULL DEFAULT false,\n    \"firedAt\" TIMESTAMP(3),\n    \"createdBy\" TEXT,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"PriceAlert_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"Holding\" (\n    \"id\" TEXT NOT NULL,\n    \"coinId\" TEXT NOT NULL,\n    \"sym\" TEXT NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"amt\" DOUBLE PRECISION NOT NULL DEFAULT 0,\n    \"avgCost\" DOUBLE PRECISION NOT NULL DEFAULT 0,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"Holding_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"ScheduledJob\" (\n    \"id\" TEXT NOT NULL,\n    \"kind\" TEXT NOT NULL,\n    \"label\" TEXT NOT NULL,\n    \"body\" TEXT NOT NULL,\n    \"target\" TEXT NOT NULL DEFAULT 'owner',\n    \"when\" TIMESTAMP(3) NOT NULL,\n    \"repeat\" TEXT NOT NULL DEFAULT 'none',\n    \"lastRun\" TIMESTAMP(3),\n    \"on\" BOOLEAN NOT NULL DEFAULT true,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"ScheduledJob_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"Setting\" (\n    \"id\" TEXT NOT NULL DEFAULT 'nova',\n    \"persona\" TEXT NOT NULL DEFAULT 'profesional',\n    \"mode247\" BOOLEAN NOT NULL DEFAULT true,\n    \"startHour\" INTEGER NOT NULL DEFAULT 8,\n    \"endHour\" INTEGER NOT NULL DEFAULT 22,\n    \"maxMsgsPerMin\" INTEGER NOT NULL DEFAULT 20,\n    \"ownerWa\" TEXT NOT NULL DEFAULT '',\n    \"aiEnabled\" BOOLEAN NOT NULL DEFAULT true,\n    \"dailySummaryOn\" BOOLEAN NOT NULL DEFAULT false,\n    \"dailySummaryHour\" INTEGER NOT NULL DEFAULT 9,\n    \"waToken\" TEXT NOT NULL DEFAULT '',\n    \"waPhoneId\" TEXT NOT NULL DEFAULT '',\n    \"waVerifyToken\" TEXT NOT NULL DEFAULT 'nova-verify',\n    \"vapidPub\" TEXT NOT NULL DEFAULT '',\n    \"vapidPriv\" TEXT NOT NULL DEFAULT '',\n    \"ghUser\" TEXT NOT NULL DEFAULT '',\n    \"ghRepo\" TEXT NOT NULL DEFAULT 'Tiendamax',\n    \"ghBranch\" TEXT NOT NULL DEFAULT 'main',\n    \"ghPath\" TEXT NOT NULL DEFAULT 'productos.json',\n    \"ghSite\" TEXT NOT NULL DEFAULT 'https://tiendamax.org',\n    \"ghToken\" TEXT NOT NULL DEFAULT '',\n    \"shopSim\" BOOLEAN NOT NULL DEFAULT true,\n    \"lowStock\" INTEGER NOT NULL DEFAULT 3,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"Setting_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"PushSub\" (\n    \"id\" TEXT NOT NULL,\n    \"endpoint\" TEXT NOT NULL,\n    \"p256dh\" TEXT NOT NULL,\n    \"auth\" TEXT NOT NULL,\n    \"ua\" TEXT NOT NULL DEFAULT '',\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"PushSub_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"ShopProduct\" (\n    \"id\" TEXT NOT NULL,\n    \"extId\" TEXT NOT NULL,\n    \"nombre\" TEXT NOT NULL,\n    \"slug\" TEXT NOT NULL DEFAULT '',\n    \"categoria\" TEXT NOT NULL DEFAULT '',\n    \"subcat\" TEXT NOT NULL DEFAULT '',\n    \"precio\" DOUBLE PRECISION NOT NULL DEFAULT 0,\n    \"stock\" INTEGER NOT NULL DEFAULT 0,\n    \"imagen\" TEXT NOT NULL DEFAULT '',\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"ShopProduct_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"StockMove\" (\n    \"id\" TEXT NOT NULL,\n    \"extId\" TEXT NOT NULL,\n    \"nombre\" TEXT NOT NULL,\n    \"kind\" TEXT NOT NULL,\n    \"delta\" INTEGER NOT NULL,\n    \"before\" INTEGER NOT NULL,\n    \"after\" INTEGER NOT NULL,\n    \"qty\" INTEGER NOT NULL DEFAULT 0,\n    \"unitPrice\" DOUBLE PRECISION,\n    \"total\" DOUBLE PRECISION,\n    \"currency\" TEXT NOT NULL DEFAULT 'USD',\n    \"note\" TEXT NOT NULL DEFAULT '',\n    \"source\" TEXT NOT NULL DEFAULT 'voz',\n    \"sync\" TEXT NOT NULL DEFAULT 'local',\n    \"commitUrl\" TEXT NOT NULL DEFAULT '',\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"StockMove_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"TradingConfig\" (\n    \"id\" TEXT NOT NULL DEFAULT 'trading',\n    \"on\" BOOLEAN NOT NULL DEFAULT false,\n    \"simMode\" BOOLEAN NOT NULL DEFAULT true,\n    \"symbols\" TEXT NOT NULL DEFAULT 'BTCUSDT,ETHUSDT,SOLUSDT',\n    \"maxPosQuote\" DOUBLE PRECISION NOT NULL DEFAULT 50,\n    \"maxPctCapital\" DOUBLE PRECISION NOT NULL DEFAULT 5,\n    \"stopLossPct\" DOUBLE PRECISION NOT NULL DEFAULT 2,\n    \"takeProfitPct\" DOUBLE PRECISION NOT NULL DEFAULT 4,\n    \"maxTradesHour\" INTEGER NOT NULL DEFAULT 3,\n    \"sniperOn\" BOOLEAN NOT NULL DEFAULT false,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"TradingConfig_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"ExchangeCredentials\" (\n    \"id\" TEXT NOT NULL,\n    \"exchange\" TEXT NOT NULL DEFAULT 'binance',\n    \"label\" TEXT NOT NULL DEFAULT 'principal',\n    \"apiKeyEnc\" TEXT NOT NULL,\n    \"apiSecEnc\" TEXT NOT NULL,\n    \"testnet\" BOOLEAN NOT NULL DEFAULT true,\n    \"on\" BOOLEAN NOT NULL DEFAULT false,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"ExchangeCredentials_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"TradeLog\" (\n    \"id\" TEXT NOT NULL,\n    \"symbol\" TEXT NOT NULL,\n    \"side\" TEXT NOT NULL,\n    \"type\" TEXT NOT NULL DEFAULT 'MARKET',\n    \"price\" DOUBLE PRECISION NOT NULL,\n    \"qty\" DOUBLE PRECISION NOT NULL,\n    \"quoteQty\" DOUBLE PRECISION NOT NULL,\n    \"result\" DOUBLE PRECISION,\n    \"mode\" TEXT NOT NULL DEFAULT 'sim',\n    \"signal\" TEXT NOT NULL DEFAULT '',\n    \"reason\" TEXT NOT NULL DEFAULT '',\n    \"status\" TEXT NOT NULL DEFAULT 'filled',\n    \"pairId\" TEXT,\n    \"orderId\" TEXT,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"TradeLog_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"SniperWatch\" (\n    \"id\" TEXT NOT NULL,\n    \"symbol\" TEXT NOT NULL,\n    \"base\" TEXT NOT NULL DEFAULT '',\n    \"quote\" TEXT NOT NULL DEFAULT '',\n    \"firstSeen\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"handled\" BOOLEAN NOT NULL DEFAULT false,\n    \"note\" TEXT NOT NULL DEFAULT '',\n\n    CONSTRAINT \"SniperWatch_pkey\" PRIMARY KEY (\"id\")\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"Contact_waId_key\" ON \"Contact\"(\"waId\");",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"Holding_coinId_key\" ON \"Holding\"(\"coinId\");",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"PushSub_endpoint_key\" ON \"PushSub\"(\"endpoint\");",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"ShopProduct_extId_key\" ON \"ShopProduct\"(\"extId\");",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"SniperWatch_symbol_key\" ON \"SniperWatch\"(\"symbol\");",
  "DO $NovaFk$\nBEGIN\n    ALTER TABLE \"Message\" ADD CONSTRAINT \"Message_contactId_fkey\" FOREIGN KEY (\"contactId\") REFERENCES \"Contact\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE;\nEXCEPTION WHEN duplicate_object THEN NULL; END\n$NovaFk$;"
];

/* Ajustes base (singletons) — INSERT idempotente con los defaults del esquema */
export const NOVA_SEED: string[] = [
  "INSERT INTO \"Setting\" (\"id\", \"updatedAt\") VALUES ('nova', NOW()) ON CONFLICT (\"id\") DO NOTHING;",
  "INSERT INTO \"TradingConfig\" (\"id\", \"updatedAt\") VALUES ('trading', NOW()) ON CONFLICT (\"id\") DO NOTHING;"
];

/* v018 — Migraciones aditivas (ALTER TABLE ... ADD COLUMN IF NOT EXISTS).
   A diferencia de NOVA_DDL (que solo corre si la tabla NO existía aún),
   estas sentencias se ejecutan SIEMPRE que la BD responde, aunque las
   tablas ya existan de un despliegue anterior — así una instalación viva
   recibe columnas nuevas sin perder datos ni requerir SQL manual. */
export const NOVA_DDL_ALWAYS: string[] = [
  "ALTER TABLE \"Setting\" ADD COLUMN IF NOT EXISTS \"waAppSecret\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Holding\" ADD COLUMN IF NOT EXISTS \"avgCost\" DOUBLE PRECISION NOT NULL DEFAULT 0;"
];
